### ISSUE TITLE
Where can I download the C++ version of Ć?

### ISSUE THREAD

**Issue by txmu** [pfusik/cito#93]
I can't wait to try installing it!

Is there a roadmap or some sort of guide to install it? I ran into a bit of a snag when I went ahead and cloned the repository, then tried to execute "make -j16" - a few pesky errors popped up.

**Comment by pfusik** [comment]
It will be released in a few weeks from now.
Please paste your errors and I'll help you build it.

**Comment by txmu** [comment]
> It will be released in a few weeks from now. Please paste your errors and I'll help you build it.

```
ubuntu@arm64:~/cito$ make -j16
cito
g++: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++2a’?
make: *** [Makefile:53: cito] Error 1
ubuntu@arm64:~/cito$
```

**Comment by txmu** [comment]
(after -std=c++20 => -std=c++2a or removed -std=c++20 ...)

```
ubuntu@arm64:~/cito$ make -j16
 cito
cito.cpp:22:10: fatal error: format: No such file or directory
   22 | #include <format>
      |          ^~~~~~~~
compilation terminated.
Transpiled.cpp:6:10: fatal error: format: No such file or directory
    6 | #include <format>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:53: cito] Error 1
ubuntu@arm64:~/cito$
```

**Comment by txmu** [comment]
```
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by pfusik** [comment]
g++ 9 does not implement enough of the C++20 standard. You need g++ 13.
On Ubuntu 22.04 this works:

    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    sudo apt install g++-13
    make CXX=g++-13

(and it's used in GitHub Actions and Travis CI).
I guess it won't work on Ubuntu 20.04.

**Comment by iahunq** [comment]
@pfusik Why did you choose such a high C++ version? Shouldn't C++11 is ideal?

**Comment by pfusik** [comment]
@iahunq The goal is to use the latest features that the target languages have. I do not want to reinvent what is already available.

Speaking of C++, it's `string_view`, `std::format`, `string::starts_with`, array `make_shared` and probably a few more. This does *not* mean that every Ć code transpiled to C++ requires C++20.
